on: [pull_request, push]

jobs:
  ci:
    uses: ./.github/workflows/shared.yaml
    with:
      runners: '["ubuntu-latest", "macos-latest"]'
      unit-test: '[{ "runner": "ubuntu-latest", "args": "--shard=1/2" }, { "runner": "ubuntu-latest", "args": "--shard=2/2" }]'
