on: [pull_request, push]

jobs:
  ci:
    uses: ./.github/workflows/shared.yaml
    with:
      runners: '["ubuntu-latest"]'
      # Uncomment to create some separate sharded jobs for unit testing
      #unit-test: '[{ "runner": "ubuntu-latest", "args": "-- --shard=1/2" }, { "runner": "ubuntu-latest", "args": "-- --shard=2/2" }]'
      # Uncomment to force complete parallelization
      fmt: '[{ "runner": "ubuntu-latest" }]'
      build: '[{ "runner": "ubuntu-latest" }]'
      lint: '[{ "runner": "ubuntu-latest" }]'
      unit-test: '[{ "runner": "ubuntu-latest" }]'
      integration-test: '[{ "runner": "ubuntu-latest" }]'