on: [pull_request, push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jdx/mise-action@v2
      - run: pnpm install
      - run: pnpm nx run-many -t build,lint,test
      - run: pnpm nx run-many -t test -c integration
